### ISSUE TITLE
FR: Super-only, and automatic font size adjustment

### ISSUE THREAD

**Issue by RhvdG** [ryanpcmcquen/obsidian-focus-mode#48]
I'd prefer the button to optionally toggle super-focus only; I have no use of the regular mode. Also, I'd like to be given the option of automatically increasing the font size (by a user defined amount) when clicking the button (or hitting the hotkey), so I would land in a iA Writer-like writing environment at once. Obviously, leaving the super focus mode should also restore the normal font size.

**Comment by ryanpcmcquen** [comment]
Custom CSS snippets (under Obsidian's appearance menu) will help you out here. As far as eliminating normal Focus Mode, I find it useful. You already have a way to go directly in to Super Focus Mode and exit immediately out of it.

**Comment by RhvdG** [comment]
I was talking about assigning superfocus to the button, optionally, which would have no drawbacks for anyone. And CSS snippets are not my thing, I am a writer.

**Comment by ryanpcmcquen** [comment]
I am anti-settings as I find them distracting, I'll put together a snippet for you and post it here.

**Comment by ryanpcmcquen** [comment]
Here's two snippets that should help:

`Bigger_font_size_in_focus_mode.css`:
```css
.focus-mode .CodeMirror,
.super-focus-mode .CodeMirror,
.focus-mode .CodeMirror *,
.super-focus-mode .CodeMirror * {
    font-size: 110%;
}
```

`Make_focus_mode_more_like_super_focus_mode.css`
```css
.focus-mode .workspace-tabs:not(.mod-active) {
    display: none;
}

.focus-mode .workspace-tab-header-container {
    padding-left: var(--size-4-8);
}
```
And here's a demo of what they do:
![focus_mode_snippets_demo_00](https://user-images.githubusercontent.com/772937/225451478-679b9f61-3495-44e2-8052-e8c9a55e81b4.gif)
